### ISSUE TITLE
Blocking other scripts from running

### ISSUE THREAD

**Issue by ThePixelDeveloper** [videlalvaro/RabbitMqBundle#283] opened 2015-07-04 13:12 UTC
Playing with this locally and can't seem to run another instance of `./app/console` while the consumer is listening. ie

``` bash
./app/console rabbitmq:consumer upload_screenshot
```

Then if I try to run

``` bash
./app/console cache:clear
```

it just hangs indefinitely. To be fair, I can't even execute 

``` bash
php ./public/index.php
```

which contains

``` php
<?php

echo 'hello world';
exit;
```

 either. Missing anything in the php configuration that would cause this?

**Comment by videlalvaro** [comment] 2015-07-05 08:47
First time I hear this. I would assume people run many instances of PHP while using this bundle.

Anyway, do you have strace (linux) or dtrace (mac) ? Perhaps try to see what's going on using those tools.

**Comment by ThePixelDeveloper** [comment] 2015-07-05 09:17
This is where it's blocking ...

```
write(4, "485\0<?xml version=\"1.0\" encoding"..., 490) = 490
recvfrom(4, "feature_set -i 1 -n show_hidden "..., 128, 0, NULL, NULL) = 37
write(4, "218\0<?xml version=\"1.0\" encoding"..., 223) = 223
recvfrom(4, "feature_set -i 2 -n max_depth -v"..., 128, 0, NULL, NULL) = 35
write(4, "216\0<?xml version=\"1.0\" encoding"..., 221) = 221
recvfrom(4, "feature_set -i 3 -n max_children"..., 128, 0, NULL, NULL) = 40
write(4, "219\0<?xml version=\"1.0\" encoding"..., 224) = 224
recvfrom(4, "status -i 4\0", 128, 0, NULL, NULL) = 12
write(4, "209\0<?xml version=\"1.0\" encoding"..., 214) = 214
recvfrom(4, "step_into -i 5\0", 128, 0, NULL, NULL) = 15
write(4, "323\0<?xml version=\"1.0\" encoding"..., 328) = 328
recvfrom(4, "eval -i 6 -- aXNzZXQoJF9TRVJWRVJ"..., 128, 0, NULL, NULL) = 58
write(4, "249\0<?xml version=\"1.0\" encoding"..., 254) = 254
recvfrom(4, "eval -i 7 -- KHN0cmluZykoJF9TRVJ"..., 128, 0, NULL, NULL) = 62
write(4, "306\0<?xml version=\"1.0\" encoding"..., 311) = 311
recvfrom(4, 
```

Looks it's something is locking a file causing the PHP CLI to block.

**Comment by videlalvaro** [comment] 2015-07-05 09:21
So if you uninstall the bundle, does this problem goes away? If the problem is reading an XML file, it doesn't seem to be related to the bundle

**Comment by ThePixelDeveloper** [comment] 2015-07-05 09:23
I've diagnosed the problem. It only happens when I've told phpStorm to listen for xdebug requests but haven't set any breakpoints. In this case I'd normally see the program just run through, but it appears it's just hanging in this instance.

**Comment by videlalvaro** [comment] 2015-07-05 09:25
Cool. I'll close the issue

**Closed by videlalvaro** 2015-07-05 09:25 UTC
